### ISSUE TITLE
Site breaks after updating to Microsoft.CodeAnalysis.CSharp 3.0

### ISSUE THREAD

**Issue by ronaldbarendse** [zpqrtbnk/Zbu.ModelsBuilder#196]
As described in issue https://github.com/umbraco/Umbraco.Cloud.Issues/issues/72#issuecomment-488692519, the NuGet package for Umbraco.ModelsBuilder 3.0.10 allows updating Microsoft.CodeAnalysis.CSharp to version 3.0.

This makes a site randomly crash however, so it might be good to limit this dependency version to version 2.x!

**Comment by zpqrtbnk** [comment]
Done as part of PR #198 and will be part of 3.1.1

**Comment by ronaldbarendse** [comment]
@zpqrtbnk Looks like this change isn't merged into the V8 packages (https://www.nuget.org/packages/Umbraco.ModelsBuilder/8.1.0) and it still crashes IIS Express when updated to 3.0+.

**Comment by zpqrtbnk** [comment]
Ouch. Will merge.

**Comment by zpqrtbnk** [comment]
Is #209
